import profile1 from '@/public/assets/hassan.svg';
import profile2 from '@/public/assets/mh.svg';
import profile3 from '@/public/assets/oldlad.svg';

export const gridData = [
  {
    id: 1,
    name: [{ profile: profile1, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'Maxim cakes and pastery (visual advert) was promoted',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 2,
    name: [{ profile: profile2, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'Maxim cakes and pastery (visual advert) was promoted',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 3,
    name: [{ profile: profile3, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'Maxim cakes and pastery (Directlink advert) was promoted',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 4,
    name: [{ profile: profile1, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'Your payment of #150,000 was succesful',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 5,
    name: [{ profile: profile3, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'You just received a visual promotion',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 6,
    name: [{ profile: profile2, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'Your advert link has been copied for promotion',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 7,
    name: [{ profile: profile1, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'You just received a details promotion',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
  {
    id: 8,
    name: [{ profile: profile2, user: 'Maharm Hassanli' }],
    userId: '#300187634',
    action: 'Your advert link has been copied for promotion',
    date: '20/09/2022',
    time: '11:52PM',
    value: false,
  },
];
